# Site settings
title: Deepender Singla blog
email: deepender281190@gmail.com
description: "Musings of a learner"
baseurl: ""
url: "http://deependersingla.github.io"
github_username:  deependersingla

# Build settings
markdown: redcarpet
permalink: pretty