# Site settings
title: Deepender thoughts
email: deepender281190@gmail.com
description: Deepender Singla Blog: Covers all my thoughts and other things which i work or think in my day
  -to-day life.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://deependet.github.io" # the base hostname & protocol for your site
github_username:  deependersingla

# Build settings
markdown: kramdown
